version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - TZ=Europe/Lisbon
      - PGTZ=Europe/Lisbon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend

  postgres-demo:
    container_name: postgres-demo
    image: postgres:16
    restart: always
    volumes:
      - ./backend/init-demo.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - TZ=Europe/Lisbon
      - PGTZ=Europe/Lisbon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
    
  redis:
    container_name: redis
    image: redis:7.2
    restart: always
    environment:
      - TZ=Europe/Lisbon
    networks:
      - backend

  backend:
    container_name: backend
    build: ./backend
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend/src:/usr/src/app/backend/src
      - ./backend/storage:/usr/src/app/backend/storage
    environment:
      - TZ=Europe/Lisbon
    networks:
      - backend
      - caddy-backend

  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/usr/src/app/frontend/src
      - ./frontend/dist:/usr/src/app/frontend/dist
    environment:
      - TZ=Europe/Lisbon
    networks:
      - caddy-frontend
  
  caddy:
    container_name: caddy
    image: caddy:2.7
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
      - ./caddy_data:/data
    networks:
      - caddy-backend
      - caddy-frontend

networks:
  backend:
    driver: bridge
  caddy-backend:
    driver: bridge
  caddy-frontend:
    driver: bridge
