version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - TZ=Europe/Lisbon
      - PGTZ=Europe/Lisbon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  postgres-demo:
    container_name: postgres-demo
    image: postgres
    restart: always
    volumes:
      - ./backend/init-demo.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - TZ=Europe/Lisbon
      - PGTZ=Europe/Lisbon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    container_name: backend
    build: ./backend
    restart: always
    depends_on:
      - postgres
    ports:
      - 3000:3000
    volumes:
      - ./backend/src:/usr/src/app/backend/src
      - ./backend/storage:/usr/src/app/backend/storage
    environment:
      - TZ=Europe/Lisbon

  frontend:
    container_name: frontend
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/usr/src/app/frontend/src
    environment:
      - TZ=Europe/Lisbon
